// Code generated by ansible/schema/codegen.py from ansible/schema/migrations.
// DO NOT EDIT. Regenerate: python3 ansible/schema/codegen.py

package rqlitestorage

type CaddyStorage struct {
	Key      string `db:"key" json:"key"`
	Value    string `db:"value" json:"value"`
	Size     int64  `db:"size" json:"size"`
	Modified int64  `db:"modified" json:"modified"`
}

func (c CaddyStorage) Table() string { return "caddy_storage" }

type CaddyLocks struct {
	Name    string `db:"name" json:"name"`
	Token   string `db:"token" json:"token"`
	Expires int64  `db:"expires" json:"expires"`
}

func (c CaddyLocks) Table() string { return "caddy_locks" }
